version: '2'

services:

  provisioner:
    image: aws-local-provisioner:latest
    environment:
      S3_HOST: http://aws-mock:3000
      SQS_HOST: http://aws-mock:3001
      SSM_HOST: http://aws-mock:3002
      SNS_HOST: http://aws-mock:3003
      KINESIS_HOST: http://aws-mock:3004
      DYNAMODB_HOST: http://aws-mock:3005
      AWS_LOCAL_TEMPLATE_PATH: /aws-local/example-assets/local_template.yaml
    volumes:
      - ./example-assets:/aws-local/example-assets
    depends_on:
      - aws-mock

  moto-provisioner:
    image: aws-local-provisioner:latest
    environment:
      MOCK_AWS_HOST: moto-aws-mock:3000
      AWS_LOCAL_TEMPLATE: |
        version: '1.0'
        resources:
          storage_bucket:
            type: bucket
            name: storage-bucket
          notifications_queue:
            type: queue
            name: notifications-queue
          notifications_topic:
            type: topic
            name: notifications-topic
          file_to_upload:
            type: s3_upload
            filename: /aws-local/example-assets/some_file.txt
            key: some_file.txt
            bucket: storage-bucket
          stream:
            type: stream
            name: event-stream
          crazy_stream:
            type: stream
            name: crazy-stream
          ssm_keys:
            type: ssm_parameter
            key: some-secret
            value: oh-so-secret
          # Sadly, moto doesn't seem to support
          #   - dynamodb_table
          #   - subscription:queue:topic
          #   - subscription:queue:bucket
    volumes:
      - ./example-assets:/aws-local/example-assets
    depends_on:
      - moto-aws-mock

  # -------- AWS Mocks --------

  aws-mock:
    image: localstack/localstack:0.8.6
    environment:
      DEFAULT_REGION: eu-west-1
      SERVICES: s3:3000,sqs:3001,ssm:3002,sns:3003,kinesis:3004,dynamodb:3005
      FORCE_NONINTERACTIVE: 'true'
      HOSTNAME: aws-mock
      HOSTNAME_EXTERNAL: aws-mock
      DEBUG: 0

  moto-aws-mock:
    image: aws-local-moto-server:latest
    build: moto_host
